apiVersion: v1
kind: Secret
data:
  password: em5uX3Bhc3M= #znn_pass
metadata:
  name: mysql-pass
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: kube-znn-db
  labels:
    app: kube-znn-db
spec:
  ports:
    - name: tcp
      port: 3306
  selector:
    app: kube-znn-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-znn-db
  labels:
    app: kube-znn-db
spec:
  selector:
    matchLabels:
      app: kube-znn-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kube-znn-db
    spec:
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb
      serviceAccountName: kubeznn
      containers:
      - image: mysql:5.6
        name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306